"""
Insight engine: reads the audit log and produces two outputs:
  1. Confidence distribution stats + per-domain breakdown  (no LLM, cheap)
  2. A knowledge-gap report generated by the LLM           (on-demand only)

The stats endpoint is called on every Insights tab load; the report is only
triggered when the user clicks "Generate Report" so we don't burn LLM quota
on every page view.
"""

import json
import logging
import os
from collections import Counter
from typing import Optional

from generation.audit_logger import AUDIT_LOG_PATH
from generation.generator import _get_provider

logger = logging.getLogger(__name__)

# How many LOW/MEDIUM queries to include in the gap-report prompt.
# Sending more gives the LLM richer context; sending fewer keeps cost low.
_GAP_SAMPLE_LIMIT = 20

_GAP_PROMPT = """\
You are a knowledge management analyst for SIX Group.

The list below shows queries that AskMe — an internal enterprise RAG system — answered \
with LOW or MEDIUM confidence, or could not answer at all. \
This means the knowledge base does not adequately cover these topics.

Analyse the queries and write a concise gap report (150-250 words) structured as:

• UNCOVERED TOPICS: bullet list of subjects the knowledge base is missing
• RECOMMENDED CONTENT: what types of documents or data should be ingested to close each gap
• PATTERNS: any notable trends (e.g. concentration in one domain, recurring terminology)

Be specific and actionable. Plain text and bullet points only — no JSON, no markdown headers.

Queries:
{queries}"""


class InsightEngine:
    """
    Stateless — instantiate once at startup; every method reads fresh from disk.
    The LLM provider is loaded lazily so the engine can be constructed even when
    no provider is configured (stats work without it; report generation will fail
    gracefully with an error message).
    """

    def __init__(self) -> None:
        self._provider = None   # loaded lazily in generate_gap_report()

    def confidence_distribution(self) -> dict:
        """
        Scans audit_log.jsonl and returns:
          distribution  : {"HIGH": n, "MEDIUM": n, "LOW": n}
          by_domain     : {domain: {"HIGH": n, "MEDIUM": n, "LOW": n}}
          total         : total number of queries logged
        Pure disk read — no LLM call.
        """
        dist   = {"HIGH": 0, "MEDIUM": 0, "LOW": 0}
        by_dom: dict = {}

        if not os.path.exists(AUDIT_LOG_PATH):
            return {"distribution": dist, "by_domain": by_dom, "total": 0}

        with open(AUDIT_LOG_PATH, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    entry = json.loads(line)
                except json.JSONDecodeError:
                    continue

                lvl = (entry.get("confidence", {}).get("level") or "LOW").upper()
                if lvl not in dist:
                    lvl = "LOW"
                dist[lvl] += 1

                # Determine domain: first citation, else first retrieval chunk
                cits  = entry.get("citations") or []
                trace = entry.get("retrieval_trace") or []
                if cits:
                    dom = cits[0].get("domain") or ""
                elif trace:
                    dom = trace[0].get("domain") or ""
                else:
                    dom = ""

                if not dom:
                    continue  # skip entries with no domain — don't pollute the chart

                if dom not in by_dom:
                    by_dom[dom] = {"HIGH": 0, "MEDIUM": 0, "LOW": 0}
                by_dom[dom][lvl] += 1

        return {
            "distribution": dist,
            "by_domain":    by_dom,
            "total":        sum(dist.values()),
        }

    def generate_gap_report(self) -> dict:
        """
        Reads the most recent LOW/MEDIUM audit entries and asks the LLM to
        identify knowledge gaps.  Returns {"report": str, "based_on": int}.
        Degrades gracefully: returns an informative message on any failure.
        """
        low_medium = []

        if os.path.exists(AUDIT_LOG_PATH):
            with open(AUDIT_LOG_PATH, "r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        entry = json.loads(line)
                    except json.JSONDecodeError:
                        continue
                    lvl = (entry.get("confidence", {}).get("level") or "LOW").upper()
                    if lvl in ("LOW", "MEDIUM"):
                        low_medium.append(entry)

        if not low_medium:
            return {
                "report":    "No LOW or MEDIUM confidence queries recorded yet — nothing to analyse.",
                "based_on":  0,
            }

        sample = low_medium[-_GAP_SAMPLE_LIMIT:]
        queries_text = "\n".join(
            f"- [{e.get('confidence', {}).get('level', 'LOW')}] {e.get('query', '').strip()}"
            for e in sample
        )
        prompt = _GAP_PROMPT.format(queries=queries_text)

        if self._provider is None:
            try:
                self._provider = _get_provider()
            except Exception as exc:
                logger.warning("Could not load LLM provider for gap report: %s", exc)
                return {
                    "report":   f"LLM provider unavailable: {exc}",
                    "based_on": len(sample),
                }

        try:
            report_text, _ = self._provider.complete(prompt)
        except Exception as exc:
            logger.warning("Gap report LLM call failed: %s", exc)
            report_text = f"Report generation failed: {exc}"

        return {"report": report_text.strip(), "based_on": len(sample)}
